### PR TITLE
Switch build backend to hatchling

### PR DESCRIPTION
**Pull request by hoechenberger**
For consistency with mne-tools projects and to ensure properly working editable installs.

### CODE REVIEW

**Review by sappelhoff — COMMENTED** [review]
https://github.com/autoreject/autoreject/wiki/How-to-make-a-release would need to be adjusted

**Comment by hoechenberger** [comment]
> https://github.com/autoreject/autoreject/wiki/How-to-make-a-release would need to be adjusted

What would need adjustment there, exactly?

**Comment by sappelhoff** [comment]
Oh, sorry @hoechenberger ... I forgot that I already made the edits in December -- nothing to change then! ✅

**Review by sappelhoff — APPROVED** [review]

**Comment by sappelhoff** [comment]
thanks @hoechenberger

**Pull request merged**
