### PR TITLE
Fix epochs plotter

### LINKED ISSUE #153: autoreject import failing with mne python master
with mne-python dev installation and autoreject pip (latest pypi) installation, `import autoreject` yields the following:

(error not present when using mne-python 0.18.2)

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-dcfa2da527e7> in <module>
----> 1 import autoreject

~/miniconda3/envs/mne/lib/python3.6/site-packages/autoreject/__init__.py in <module>
      1 __version__ = '0.2'
      2 
----> 3 from .autoreject import _GlobalAutoReject, _AutoReject, AutoReject
      4 from .autoreject import RejectLog, read_auto_reject
      5 from .autoreject import compute_thresholds, validation_curve, get_rejection_threshold

~/miniconda3/envs/mne/lib/python3.6/site-packages/autoreject/autoreject.py in <module>
     25                     _get_picks_by_type, _pprint)
     26 from .bayesopt import expected_improvement, bayes_opt
---> 27 from .viz import plot_epochs
     28 
     29 _INIT_PARAMS = ('consensus', 'n_interpolate', 'picks',

~/miniconda3/envs/mne/lib/python3.6/site-packages/autoreject/viz.py in <module>
     18 from mne.io.pick import pick_types, channel_type
     19 from mne.io.proj import setup_proj
---> 20 from mne.viz.utils import (figure_nobar, _toggle_proj, _toggle_options,
     21                            _layout_figure, _channels_changed,
     22                            _plot_raw_onscroll, _onclick_help, plt_show,

ImportError: cannot import name '_layout_figure'



```

### PR DESCRIPTION
**Pull request by jasmainak**
closes #153 

should be merged in conjunction with https://github.com/mne-tools/mne-python/pull/6855

### CODE REVIEW

**Comment by jasmainak** [comment]
@agramfort @larsoner the CIs pass here with my branch of the PR on mne-python

**Comment by jasmainak** [comment]
CIs are happy @agramfort

**Comment by davestanley** [comment]
This update produced an error for me - the plot_epochs function in my 0.19 build of MNE could not accept the epoch_colors argument.  I uninstalled and reinstalled using `pip install -U mne`.

Incase others encounter the same issue, I was able to fix by installing the latest version of master (e.g., `pip install -U https://api.github.com/repos/mne-tools/mne-python/zipball/master`)

**Comment by agramfort** [comment]
give us few days to release 0.19.1. Hopefully by the end of the week

>

**Pull request merged**
