### PR TITLE
[MRG] Fix CIs

### PR DESCRIPTION
**Pull request by sappelhoff**
- trying to repair caching
- testing only on python 3.5 and higher
- adjusting docs

### CODE REVIEW

**Comment by agramfort** [comment]
you need to fix circle too

**Comment by sappelhoff** [comment]
it's a bit weird, that `pytest --cov=autoreject` gives me a coverage of 67%, while `nosetests . --with-coverage` yields 62%. :thinking: ... and in the online CI it's something above 90 :scream: 


# pytest
```
----------- coverage: platform linux, python 3.6.8-final-0 -----------
Name                                  Stmts   Miss  Cover
---------------------------------------------------------
autoreject/__init__.py                    6      0   100%
autoreject/autoreject.py                489     50    90%
autoreject/bayesopt.py                   41      8    80%
autoreject/ransac.py                    114      8    93%
autoreject/tests/test_autoreject.py     167      1    99%
autoreject/tests/test_bayesopt.py        11      0   100%
autoreject/tests/test_ransac.py          29      0   100%
autoreject/tests/test_utils.py           51      0   100%
autoreject/tests/test_viz.py             27      0   100%
autoreject/utils.py                     239     26    89%
autoreject/viz.py                       868    581    33%
---------------------------------------------------------
TOTAL                                  2042    674    67%
```

# nosetests

```
Name                       Stmts   Miss  Cover
----------------------------------------------
autoreject/__init__.py         6      0   100%
autoreject/autoreject.py     489     50    90%
autoreject/bayesopt.py        41      8    80%
autoreject/ransac.py         114      8    93%
autoreject/utils.py          239     26    89%
autoreject/viz.py            868    581    33%
----------------------------------------------
TOTAL                       1757    673    62%
----------------------------------------------------------------------
Ran 8 tests in 71.838s

```

**Comment by agramfort** [comment]
@jasmainak merge if you're happy

thx @sappelhoff

**Comment by jasmainak** [comment]
Looks great! Thanks @sappelhoff :)

**Pull request merged**
