### PR TITLE
[MRG] DOC: improve recommendation in FAQ

### LINKED ISSUE #229: Inconsistency in autoreject docs?
Hi, in the first code cell of the [FAQ section](https://autoreject.github.io/faq.html) of the docs, it is recommended to do the following:
```
reject = get_rejection_threshold(epochs)
ica.fit(epochs, reject=reject)
```
However, in the [MNE documentation](https://mne.tools/stable/generated/mne.preprocessing.ICA.html?highlight=ica%20fit#mne.preprocessing.ICA.fit), regarding the `reject` parameter of `ICA.fit`, it is explicitly said  that "It only applies if inst is of type Raw.". Thus, the recommendation above would not yield what intended. Can someone clear this up?

### PR DESCRIPTION
**Pull request by jasmainak**
closes #229

### CODE REVIEW

**Comment by jasmainak** [comment]
looks like tests are failing due to MNE. @hoechenberger what would you recommend?

**Comment by jasmainak** [comment]
or maybe @adam2392 ?

**Comment by adam2392** [comment]
You have to install pooch in order to fetch datasets now

**Comment by jasmainak** [comment]
but I don't get why installing MNE does not install pooch ...

**Review by agramfort — APPROVED** [review]

**Comment by adam2392** [comment]
Because the datasets module isn't used by everyone necessarily and @agramfort wanted us to make sure that all core functionality was preserved with just a numpy/scipy install. 

The pooch overhaul greatly simplifies life in the dataset fetching land tho.

**Comment by jasmainak** [comment]
To me, it's not a soft dependency if you can't run any example without the package. Almost all MNE examples use the `datasets` module ...

But I can live with it

**Comment by adam2392** [comment]
I agree for my use-cases. The issue was that there are some users that solely use MNE in some server context and only install numpy/scipy w/ it. So there is the desire to keep the install as light-weight as possible.

**Comment by jasmainak** [comment]
@agramfort feel free to merge once CIs are happy

**Comment by agramfort** [comment]
please merge when green

thx @jasmainak

**Comment by jasmainak** [comment]
thanks for reviewing @agramfort !

**Pull request merged**
