### PR TITLE
fix coverage report

### PR DESCRIPTION
**Pull request by sappelhoff**
fixes https://github.com/autoreject/autoreject/pull/165#issuecomment-584266307

This should make pytest measure the true coverage again (~93% instead of 23%)

### CODE REVIEW

**Comment by sappelhoff** [comment]
i don't get it ... -.-

**Comment by agramfort** [comment]
see how I did it recently here:

https://github.com/braindecode/braindecode/blob/master/.travis.yml#L35

you need this:

https://github.com/braindecode/braindecode/blob/master/.travis.yml#L21

**Comment by sappelhoff** [comment]
well ... now the coverage is at 99.65, because test files are covered as well. I think it's okay @jasmainak

**Comment by sappelhoff** [comment]
resumé: Using coverage.py solved everything.

I have no clue why pytest-cov was not running on travis ... locally, I had no problems.

**Comment by jasmainak** [comment]
Thanks @sappelhoff 

But I don't see any coverage.py in the diff?

**Comment by sappelhoff** [comment]
> EDIT: ahh, it's a pip installable package?

yes :-) ... and apparently it works well together with pytest-cov.

**Pull request merged**
