### PR TITLE
[MRG] fix/ci: do all doc building in single job

### PR DESCRIPTION
**Pull request by sappelhoff**
hopefully the last PR in the series #247 #248

See conversation starting from https://github.com/autoreject/autoreject/pull/248#issuecomment-974847062

in brief: Now that we switched the "executor" in CircleCI from Docker (single core, 2-4GB RAM) to a "linux machine" (dual core, 7.5GB RAM), the previous fix of executing examples in parallel in distinct jobs should no longer be necessary to meet the new <1h build duration goal for the free plan CircleCI service. -> So revert to doing all in a single job ... but with new executor.

In all three PRs, this leaves us with the following enhancements compared to before:

- faster and more stable builds (no more "occasional" timeouts)
- regular builds (weekly for docs, daily for tests)
- several other smaller and misc fixes

Also I noticed that `venv` is cooler than I thought :wink: and the parallel jobs might come in handy some time in the future again ... who knows.

EDIT:

takes 15min now: 
image

### CODE REVIEW

**Comment by sappelhoff** [comment]
I added some minor cleanup commits. Should be relatively straight forward to review still (all related docs or cosmetic changes). Maybe the biggest thing of those: I added the sphinx-copybutton extension that we also use in mne and mne-bids -- to get nice copy buttons in the docs.

**Comment by jasmainak** [comment]
15 minutes total build times ... oh yessssss!!! that's more like it :)

**Comment by jasmainak** [comment]
> I added the sphinx-copybutton extension that we also use in mne and mne-bids -- to get nice copy buttons in the docs.

this is awesome!!!

**Comment by jasmainak** [comment]
Thanks @sappelhoff !!! 🥳 🥳 🥳 🕺 🍺 🍺

**Pull request merged**
