### PR TITLE
MAINT: Use pathlib methods

### PR DESCRIPTION
**Pull request by larsoner**
Should fix https://dev.azure.com/autoreject/autoreject/_build/results?buildId=214&view=logs&j=c2fabf20-0dae-5771-2529-62cd5b113ff9&t=d66eb9f1-8d44-594c-8e02-393c3fa885da

### CODE REVIEW

**Comment by larsoner** [comment]
I also added a branch protection rule that CIs must pass and auto-merge, so in theory this should auto-merge when green!

**Review by sappelhoff — APPROVED** [review]

**Comment by jasmainak** [comment]
Just to clarify, the auto-merge happens when the PR has been approved by a collaborator?

**Comment by larsoner** [comment]
Someone with write permissions needs to click a button saying "squash and merge when requirements met" then you can enter the squash+merge message just like when clicking the green button. I did this already but feel free to "disable auto-merge" and redo it yourself to see how nice it is :)

**Comment by jasmainak** [comment]
Understood and yep I agree it is nice :) Thanks for enabling it! I think I tried this for hnn-core at some point but CIs started failing when I did this. Maybe time to give it another shot.

**Review by agramfort — APPROVED** [review]

**Pull request merged**
