### PR TITLE
Make data augmentation optional

### PR DESCRIPTION
**Pull request by jasmainak**
@jbschiratti  reported to me that sometimes you just want to know the channel-level thresholds even if you don't have the channel locations: for example in the case of intracranial EEG data. Here is a small PR to add a boolean parameter `augment` to make data augmentation optional

### CODE REVIEW

**Comment by dengemann** [comment]
No objections. Sounds good.

**Comment by jbschiratti** [comment]
Thank you @jasmainak !

**Comment by jasmainak** [comment]
@jbschiratti `LocalAutoreject` and `LocalAutorejectCV` will interpolate for you when you use the `transform` method. It's a bit more complicated to make it work when channel locations are missing. I think Denis' PR here: https://github.com/autoreject/autoreject/pull/71 will help you with that. But we need to find a time to sit down and get it done :)

**Comment by jasmainak** [comment]
I'm getting a kick out of merging PRs today ;)

**Pull request merged**
