### PR TITLE
fix coverage report

### PR DESCRIPTION
**Pull request by sappelhoff**
coverage report is currently at 0% ... I hope this PR fixes it.

### CODE REVIEW

**Comment by sappelhoff** [comment]
Travis does not get triggered unfortunately. No clue why and I don't have rights for autoreject to look into it.

Perhaps it'll show up later.

Travis is consistently the slowest CI on all the repos I have seen :-/

**Comment by jasmainak** [comment]
I can see your build here: https://travis-ci.org/github/autoreject/autoreject/jobs/706999380

not sure why it doesn't figure in the checkboxes above

**Comment by sappelhoff** [comment]
okay, thanks for the link -> that's enough to make it work :)

**Comment by sappelhoff** [comment]
hehe, raised coverage b< 94% with a single PR @jasmainak 

ready for merge

**Comment by jasmainak** [comment]
Perfect, thanks a ton @sappelhoff !!

**Pull request merged**
