### PR TITLE
Run CI regularly and concurrently, fix deletion of projections

### PR DESCRIPTION
**Pull request by sappelhoff**
running the circleci build job regularly will ensure that the "dev docs" are always available as circleci build artifacts. Else CircleCi will delete them after some time and they become unavailable, see https://github.com/autoreject/autoreject/issues/246#issuecomment-971534484

There are some unrelated test failures probably due to upstream changes in MNE. I added a change that now also runs the test suite (not just docs build) regularly, so that such issues can be caught earlier.

### CODE REVIEW

**Comment by sappelhoff** [comment]
We have the old problem of CircleCI build timing out after 1 hour of running. The examples just take way too long to run unfortunately. cc @jasmainak @agramfort

**Comment by jasmainak** [comment]
@sappelhoff looks like CircleCI changed their pricing plan/model. I'll look into this

Could we do this in the old fashioned way where we have a dropdown? I fear this CircleCI method is not sustainable or discoverable. Have had the issue where many people didn't realize that the dev docs exist because they didn't go via the readme page

**Comment by sappelhoff** [comment]
> Could we do this in the old fashioned way where we have a dropdown? I fear this CircleCI method is not sustainable or discoverable. Have had the issue where many people didn't realize that the dev docs exist because they didn't go via the readme page

yeah we should do a dropdown as discussed in #228 and #234 ... but that'd take about one hour and some brain capacity :-)

this PR was 10 minutes and no brain capacity so I thought I quickly contribute it

**Comment by sappelhoff** [comment]
> @sappelhoff looks like CircleCI changed their pricing plan/model. I'll look into this

Seems like it :|

I found the info here: https://circleci.com/docs/2.0/configuration-reference/#jobs

> Note: Jobs have a maximum runtime of 1 (Free), 3 (Performance), or 5 (Scale) hours depending on pricing plan. If your jobs are timing out, consider upgrading your pricing plan or running some of them concurrently using workflows.

so we need to:

- speed up the examples (e.g., fewer channels, or epochs, ...)
- use circleci "concurrency" in whatever way
- or both

Do you think that could be done in a separate PR? I don't think I have the time to do it here, and this PR at least contains some fixes

**Comment by sappelhoff** [comment]
Ok, I know I just said above that I can't do it, but I think the way to go is to split up the CircleCI jobs into:

1. setup
2. build example 1
3. build example 2
4. build example N
5. finish

all of this using `PATTERN=<REGEX_TO_SELECT_MY_TUTORIAL> make html_dev-pattern`

and circleci features:

- https://circleci.com/blog/persisting-data-in-workflows-when-to-use-caching-artifacts-and-workspaces/
- https://circleci.com/blog/decrease-your-build-times-by-running-jobs-in-parallel-with-workflows/

**Comment by jasmainak** [comment]
@sappelhoff just so I understand correctly, in the "finish" step you have all the artifacts, so theoretically I could take the outputs from this step and push to a dev folder in autoreject.github.io ? Just so I know I don't have to change things too much when I make the PR for that

**Comment by sappelhoff** [comment]
> just so I understand correctly, in the "finish" step you have all the artifacts, so theoretically I could take the outputs from this step and push to a dev folder in autoreject.github.io ? Just so I know I don't have to change things too much when I make the PR for that

yes :-) from the outside, nothing really changes --> the "finish" step will have the same artifacts that are currently held by the "build" step

all I am doing is computing each example in a separate job, in parallel ... and then stitching them together in the "finish" job.

it's just a small debugging hell, as expected - but I think it will work and speed up circleci by a lot

**Comment by jasmainak** [comment]
I can see you are having fun ;-)

also, do we start from a clean slate with each job. I'm worried that if there is a cache from previous job, it might cause debugging issues. I'd rather build every example in every pull request rather than trying to intelligently figure which examples changed (like MNE does). The lower the maintenance burden the better.

**Comment by sappelhoff** [comment]
> also, do we start from a clean slate with each job. I'm worried that if there is a cache from previous job, it might cause debugging issues. I'd rather build every example in every pull request rather than trying to intelligently figure which examples changed (like MNE does). The lower the maintenance burden the better.

yes, each circleci run will fully run each example and if one example is broken, I expect the "docbuild-N" job (for the nth example) AND the "final" job to fail. It's just that in "final", no example will be actually run --> "final" will restore caches from the different "docbuild" jobs and then realize there is no need to build something and just stitch it together, producing the artifact

**Comment by jasmainak** [comment]
This is very nice, thanks @sappelhoff ! :-) Saves me the pain of having to decide which examples need to be shortened

**Comment by sappelhoff** [comment]
I am happy that it works now :sunglasses:

**Pull request merged**
