### PR TITLE
Sort Autoreject.picks to avoid AssertionError

### PR DESCRIPTION
**Pull request by paulcbogdan**
I describe the issue being fixed here: https://github.com/autoreject/autoreject/issues/309#issuecomment-1689276690

### CODE REVIEW

**Comment by jasmainak** [comment]
Thanks! Do you mind update `whats_new.rst` so I can credit you in the next release ?

**Comment by paulcbogdan** [comment]
Sounds good, I updated it. Feel free to change what I put if it doesn't sound proper

**Comment by jasmainak** [comment]
Thanks a lot @paulcbogdan !

**Comment by jasmainak** [comment]
looks like the failing tests are MNE related. @larsoner any clue?

**Pull request merged**
