### PR TITLE
For RANSAC multiprocessing: iterate over n_jobs, not n_epochs

### LINKED ISSUE #277: Possible bug in RANSAC, job distribution calculated wrong
While checking the code I stumbled across the following thing. I'm not sure if it's a bug, as I'm not very familiar with RANSAC.

https://github.com/autoreject/autoreject/blob/f1f3536b2f73bee16db3134a312c7fcd2ae25a59/autoreject/ransac.py#L204-L209

Here we get a bunch of random subsets of channels for different jobs. Then we also split up the epochs for different jobs. Then we zip them and run them in parallel.

However, the two variables are of different length. If we e.g. have 29 Epochs and `n_jobs=2`,  `self.ch_subsets_ ` will have 15 entries, whereas `epoch_idxs` has only 2. Therefore the iterator later will only be run two times instead of 15, as `zip` truncates to the shortes iterator parameter. Similarly, if I put `n_jobs=29`, the behaviour reverses, `self_ch_subsets=1` and `epochs_idxs=29`.

I think this is a critical bug, and the random channel subsets should be calculated w.r.t to the number of jobs. ~~However, I don't understand why not each epoch has their own random channel subset, i.e. why this should be dependend on `n_jobs`~~ apparently this is done to get different random seeds in the jobs (#136 ). This might also explain why I'm getting slightly different results for different number of jobs. 

this was introduced in #138

Also `_get_mappings` is running extremely slow (magnitudes longer than the ransac correlation calculations), and the mapping re-calculated for each job, is that intended? Because of this the calculation time is actually increasing when settings `n_jobs>1`

### PR DESCRIPTION
**Pull request by skjerns**
closes #277

### CODE REVIEW

**Comment by jasmainak** [comment]
does this fix the problem? any chance of adding a tiny test?

**Comment by agramfort** [comment]
did it change the results eg on the sample data? does it seem to help?

**Comment by skjerns** [comment]
> did it change the results eg on the sample data? does it seem to help?

in helps in so far as that it now computes correlations for all epochs, not just a subset



> does this fix the problem? any chance of adding a tiny test?

I'll work on a test :) maybe also some real testing with articially noisy channels

**Comment by skjerns** [comment]
One more question w.r.t the RANSAC algorithm: Should it not take a different random subset for each epoch? Currently if `n_jobs=1` it will select a single subset of 50 channels to estimate bad channels. There is a significant likelihood to accidentially miss a bad channel. Does this make sense at all?

**Comment by jasmainak** [comment]
I think here you are getting multiple subsets: https://github.com/autoreject/autoreject/blob/f1f3536b2f73bee16db3134a312c7fcd2ae25a59/autoreject/ransac.py#L131-L133 

By the way, I had compared the results in my implementation to the Matlab implementation of the PREP pipeline for at least one dataset and the results matched up to the decimal point. 

The only bug that may have been introduced is the parallelization. You can have a simple test that compares `n_jobs=1` to `n_jobs = 2`

**Comment by jasmainak** [comment]
> Is there a paper about RANSAC in MEEG? I find the original paper difficult to translate to MEEG work

We implemented only the RANSAC algorithm of the PREP pipeline. It only needs an interpolation function ... EEGLAB has spline interpolation for EEG but in MNE we have interpolation based on spherical harmonics for MEG implemented as well

**Comment by skjerns** [comment]
Upon closer inspection the current RANSAC implementation for `n_jobs>1` will create completely wrong results. I'll make a larger PR soon to address and fix this.

Only example:

https://github.com/autoreject/autoreject/blob/f1f3536b2f73bee16db3134a312c7fcd2ae25a59/autoreject/ransac.py#L26-L29

Here we iterate over idxs using `enumerate`, however, we also access the `epochs.get_data()` with the index of enumerate and not with the actual index of the channel. Therefore, for each job split, the same channels will be correlated.

**Comment by sappelhoff** [comment]
@skjerns can this be closed because in #280 you are doing a more thorough fix?

**Pull request closed without merging**
