### PR TITLE
Error -> warning for NO_DATA or TOO_SHORT

### PR DESCRIPTION
**Pull request by jasmainak**
closes https://github.com/autoreject/autoreject/issues/37

@fraimondo do you have time to review. It seems related to your PR https://github.com/autoreject/autoreject/pull/24.

@ramonapariciog does this fix your problem?

### CODE REVIEW

**Comment by fraimondo** [comment]
I'll review it this afternoon.

**Comment by jasmainak** [comment]
Thanks!

**Comment by fraimondo** [comment]
Well, this introduces the bug again.

The problem was that if you select epochs to clean, then the drop_log still refers to the full epochs log and not the selected epochs.

You should keep line 39 and 41 from the previous code:

`drop_log = [epochs.drop_log[x] for x in epochs.selection]`

` for drop in drop_log`

**Comment by jasmainak** [comment]
@fraimondo take a look at this line [here](https://github.com/jasmainak/autoreject/blob/b057848c6f3978a74ce82fe95cc7505cab86204a/autoreject/autoreject.py#L40). It has `!= ['IGNORED']` which is basically doing the same thing as `epochs.selection`. Do you have a script to reproduce the bug on this branch?

**Comment by fraimondo** [comment]
This is after I call `epochs.drop_bad()`

```Python
In [28]: len(epochs)
Out[28]: 808

In [29]: len(epochs.drop_log)
Out[29]: 823

In [30]: np.unique([x for x in epochs.drop_log if len(x) > 0])
Out[30]: 
array(['BAD boundary', 'IGNORED', 'NO_DATA'], 
      dtype='<U12')

In [31]: np.unique([x for x in [epochs.drop_log[i] for i in epochs.selection] if len(x) > 0])
Out[31]: array([], dtype=float64)
```

The next test if I select a some epochs to clean.

```
In [34]: t_epochs = epochs[idx]

In [35]: len(t_epochs)
Out[35]: 100

In [36]: len(t_epochs.drop_log)
Out[36]: 823

In [37]:  np.unique([x for x in t_epochs.drop_log if len(x) > 0])
Out[37]: 
array(['BAD boundary', 'IGNORED', 'NO_DATA'], 
      dtype='<U12')

In [38]:  np.unique([x for x in [t_epochs.drop_log[i] for i in t_epochs.selection] if len(x) > 0])
Out[38]: array([], dtype=float64)
```

What it does not looks correct for me is that no matter what, the code always looks at the full drop_log and not the actual drop_log of the epochs being sent to clean.

**Comment by jasmainak** [comment]
> What it does not looks correct for me is that no matter what, the code always looks at the full drop_log and not the actual drop_log of the epochs being sent to clean.

But this is why you have `drop != ['IGNORED']`. This prevents the code from looking at the full drop_log, no?

**Comment by fraimondo** [comment]
I barely remember how I used this, but I know I was trying to fit on a few epochs to optimise speed, and then correct the entire data.

With water-based EEG, sometimes after 30 minutes, the signal quality gets worse. That’s why it might be a good idea to fit the criteria using only the first half of the epochs. In my case, sometimes I work with even 3000 epochs, which will not run fast, and it won’t be a great gain to use all the data.

Now that it became a warning, then I guess it will run anyways. Although I still do not agree in the case that you first do a manual epoch selection for example.

One of the things we are working with is simultaneous TDCS and EEG. When the TDCS is on, we want to ignore this epochs, but the drop log should be something different than [‘IGNORED’]. And I won’t fit that into autoreject.

It is just a semantic issue for me. If I use auto reject on a subset of epochs, I don’t expect it to look at any information from other epochs that I did not pass, not even the drop_log, otherwise, the warning message won’t be taken seriously.

**Comment by dengemann** [comment]
@fraimondo we just discuss with Mainak. To me requiring epochs to be preloaded and using the epochs.drop method -- instead of directly indexing --- is the solution. We would remove this warning / error and MNE gets informed about our dropping and handles the drop_log, while we don't mess with it. Can you follow?

**Comment by fraimondo** [comment]
Not really, but if the warning is removed, then it’s fine. I’m just saying that the warning is not always true depending on the use case.

**Comment by dengemann** [comment]
Thanks Mainak! Now let's do another one to use epochs.drop for final discarding of epochs.

**Pull request merged**
