### PR TITLE
Drop NOSE module in favor of PYTEST

### LINKED ISSUE #163: switch tests from nose to pytest
see: https://twitter.com/tirkarthi/status/1219700384777695237

cc @sappelhoff

### PR DESCRIPTION
**Pull request by sappelhoff**
closes #163 

Dropping the nose module, because it is not actively maintained. Moving to pytest!

using a mixture of:
- nose2pytest
- global search+replace
- manual fiddling

I tried to be as minimal as possible.

### CODE REVIEW

**Comment by jasmainak** [comment]
This is fantastic and a great way to switch over! Thanks @sappelhoff for taking the initiative. The diff looks pretty good to me but there are failing tests

**Comment by sappelhoff** [comment]
should be good now :+1: Let's wait for the doc build, but otherwise, this is ready for merge

**Comment by jasmainak** [comment]
Excellent, thanks @sappelhoff !

**Comment by jasmainak** [comment]
oops @sappelhoff somehow the coverage report is broken. Any idea what went wrong?

**Pull request merged**
