### PR TITLE
Fixing pickling of AutoReject objects

### PR DESCRIPTION
**Pull request by hubertjb**
This PR fixes issue #192.

### CODE REVIEW

**Comment by jasmainak** [comment]
Looks like the CI fails due to an unrelated problem. But we can't merge the PR with CIs failing. Are you able to reproduce the problem locally on your machine? I can't seem to reproduce with MNE master ...

**Comment by jasmainak** [comment]
also don't forget to update `whats_new` !

**Comment by hubertjb** [comment]
@jasmainak weird, can't reproduce that either on my side. I can investigate a bit more tomorrow.

**Comment by jasmainak** [comment]
Thank you so much!

**Comment by hubertjb** [comment]
Quick update: after a little more digging, it looks like the error happens when mne tries to convert the default color values to be used passed by autoreject. In the stable version, there used to be a check before trying to convert the color value to an RGBA value: https://github.com/mne-tools/mne-python/blob/4944aa28c5abdad44cdab2293955fd73e29da683/mne/viz/epochs.py#L1185

In mne-master though, there is no check before the conversion, and so the function tries to convert `None` to an RGBA value: 
https://github.com/mne-tools/mne-python/blob/ef2a2e491763db89d7411eee4c0dd49b1c8032ee/mne/viz/_figure.py#L2037

**Comment by jasmainak** [comment]
woops, looks like I missed [@drammock's comment](https://github.com/mne-tools/mne-python/pull/8381#issuecomment-721303828) between my emails. @drammock is there an easy fix for this?

**Comment by agramfort** [comment]
Thx @hubertjb

**Comment by hubertjb** [comment]
> Thx @hubertjb

That was an efficient fix. Thanks @agramfort and @jasmainak !

**Comment by jasmainak** [comment]
Thanks @hubertjb ! :)

**Pull request merged**
