### PR TITLE
[MRG, BUG] fix long computation time in example

### PR DESCRIPTION
**Pull request by alexrockhill**
Related to https://github.com/autoreject/autoreject/pull/205

This example takes ~70 minutes to run for some reason. This fixes that by picking a subset of channels but leaving the one that really makes the example.

### CODE REVIEW

**Comment by alexrockhill** [comment]
70 minutes down to 40 seconds with all the same content, looks good to go by me https://774-59485140-gh.circle-artifacts.com/0/html/auto_examples/plot_auto_repair.html#sphx-glr-auto-examples-plot-auto-repair-py

**Comment by jasmainak** [comment]
I think we should fix the root of the problem, not change the example. This example reproduces Figure 1 of the paper. It seems to be a config issue with CircleCI

**Comment by alexrockhill** [comment]
Perhaps a RAM issue as mentioned in another comment, making it use swap. Wouldn't it be easier to leave it to execute in 30 seconds rather then 10 minutes and say that the paper could be reproduced without the decimation?

**Comment by agramfort** [comment]
did you run memory_profiler locally to see how much RAM the example uses?
CircleCI has 4GB of RAM AFAIK.

could it be a regression in mne-python?

>

**Comment by jasmainak** [comment]
no memory issues I think @agramfort 

image

**Comment by jasmainak** [comment]
I enabled this option:

image

it should speed things up quite a bit, specially when folks are pushing multiple commits one after the other.

**Comment by jasmainak** [comment]
@alexrockhill I'm going to close this issue for now, I think it was some temporary slowness you noticed because of pushing multiple times. We can reopen if the issue persists.

**Comment by alexrockhill** [comment]
Sounds good, if it's working fast it's working fast, it was just really slow on many CI runs so the servers could have been running slow or something but they definitely weren't all simultaneous so that doesn't seem like the most likely cause of it being slow.

**Pull request closed without merging**
